stages:
  - build
  - deploy
dev-build:
  stage: build
  image: node:18.12.1
  script: 
    - yarn set version 1.22.19
    - yarn install
    - echo "REACT_APP_BASE_URL="$DEV_REACT_APP_BASE_URL >> .env
    - echo "REACT_APP_LOCAL_URL="$REACT_APP_LOCAL_URL >> .env
    - echo "REACT_APP_AUTH_TOKEN="$REACT_APP_AUTH_TOKEN >> .env
    - CI=false yarn build
    - aws s3 cp build/ $DEV_S3_ORIGIN_BUCKET/ --recursive
    - aws cloudfront create-invalidation --distribution-id $DEV_CLOUDFRONT_ID --paths "/*"
  only:
    - develop
  tags:
    - shell-runner-1


qa-build:
  stage: build
  image: node:18.12.1
  script: 
    - yarn set version 1.22.19
    - yarn install
    - echo "REACT_APP_BASE_URL="$QA_REACT_APP_BASE_URL >> .env
    - echo "REACT_APP_LOCAL_URL="$REACT_APP_LOCAL_URL >> .env
    - echo "REACT_APP_AUTH_TOKEN="$REACT_APP_AUTH_TOKEN >> .env
    - CI=false yarn build
    - aws s3 cp build/ $QA_S3_ORIGIN_BUCKET/ --recursive
    - aws cloudfront create-invalidation --distribution-id $QA_CLOUDFRONT_ID --paths "/*"
  only:
    - qa
  tags:
    - shell-runner-1


uat-build:
  stage: build
  image: node:18.12.1
  script: 
    - yarn set version 1.22.19
    - yarn install
    - echo "REACT_APP_BASE_URL="$UAT_REACT_APP_BASE_URL >> .env
    - echo "REACT_APP_LOCAL_URL="$REACT_APP_LOCAL_URL >> .env
    - echo "REACT_APP_AUTH_TOKEN="$REACT_APP_AUTH_TOKEN >> .env
    - CI=false yarn build
    - aws s3 cp build/ $UAT_S3_ORIGIN_BUCKET/ --recursive
    - aws cloudfront create-invalidation --distribution-id $UAT_CLOUDFRONT_ID --paths "/*"
  only:
    - uat
  tags:
    - shell-runner-1